# Generated by Django 4.1.7 on 2026-02-04 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_calories', models.IntegerField(default=0)),
                ('total_duration', models.IntegerField(default=0, help_text='Total duration in minutes')),
                ('total_activities', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('period', models.CharField(default='all_time', help_text='weekly, monthly, all_time', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='users.user')),
            ],
            options={
                'db_table': 'leaderboard',
                'ordering': ['-total_calories'],
                'unique_together': {('user', 'period')},
            },
        ),
    ]
