# Generated by Django 4.1.7 on 2026-02-04 15:51

from django.db import migrations


def populate_user_fields(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        # Split name into first_name and last_name
        name_parts = user.name.split(' ', 1)
        user.first_name = name_parts[0] if len(name_parts) > 0 else ''
        user.last_name = name_parts[1] if len(name_parts) > 1 else ''
        
        # Create username from email (part before @)
        user.username = user.email.split('@')[0]
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_first_name_user_last_name_user_username'),
    ]

    operations = [
        migrations.RunPython(populate_user_fields),
    ]
