# Generated by Django 4.1.7 on 2026-02-04 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('running', 'Running'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('weightlifting', 'Weightlifting'), ('yoga', 'Yoga'), ('other', 'Other')], max_length=50)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('calories', models.IntegerField(help_text='Calories burned')),
                ('distance', models.FloatField(blank=True, help_text='Distance in kilometers', null=True)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.user')),
            ],
            options={
                'db_table': 'activities',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
